### ISSUE TITLE
Controller decoration order matters

### ISSUE THREAD

**Issue by lwallent** [Romakita/ts-express-decorators#117]
## Informations

Type | Version
---|---
Improvement | 2.3.x

****

## Description
When decorating a Controller with _name_ or _description_ for the generated Swagger UI, order matters right now.

Decorators are called bottom-to-top. In order for the`@Name` and `@Description` decorators to handle Controllers correctly it is currently necessary to have the `@Controller` decorator at the bottom:

```typescript
   @Name("Users")
   @Description('The User Service')
   @Controller("/users")
   export class UsersCtrl { }
```  
This order will ensure that `@Name` and `@Description` handles the UserCtrl as a Controller.

## Todos
We should probably do one of the following things:

- [ ] Describe this order in the documentation, or 
- [ ] Create a separate decorator for creating Swagger Tags, or
- [ ] Pick up the Controller knowledge in the decorator evaluation step - as this is done top-to-bottom before the decorators are called.

**Comment by Romakita** [comment]
Hi @lwallent ,

I thinks it's just becauce you have that in the decorator:

```typescript
export function Description(description: string) {

    return (...args: any[]) => {
        const [target] = args;
        const type = getDecoratorType(args);
        switch (type) {
            case "parameter":
                return BaseParameter({description})(...args);
            case "method":
                return Operation({description})(...args);
            case "class": 
                if (ControllerRegistry.has(target)) return Tag({description})(...args);
            default:
                return Schema({description})(...args);
        }
    };
}
```
> if (ControllerRegistry.has(target)) is necessary ?

Anyway, the target is to use the decorator without order of use :). 

Thanks @lwallent ;) for your issue,
Romain

**Comment by lwallent** [comment]
Hi @Romakita,

Yes I became aware of the ControllerRegistry check introducing an order dependency of the decorators.
 
I agree that the order should not matter :-)

I just thought I would create an issue until I get it fixed as the `@Name` decorator currently throws an Error if placed incorrectly - meaning that if you write:

```
@Controller("/users")
@Name("Users")
export class UsersCtrl { }
```
an error is thrown ;-(

To answer your question whether the check is necessary: 
Decorator type _class_ should normally end in a Schema type description (definitions) where as on the controller (also type class) it should be added to the Tag array (at least in my opinion ;-) ) 
  
```
export interface Spec {
  ...
  definitions?: {[definitionsName: string]: Schema }; 
  ...
  tags?: Tag[];
}
```

Hope this explains.
KR
Lasse

**Comment by Romakita** [comment]
Ok thanks @lwallent ,

I'll test your example. Maybe I'll find a fix XD
Romain
