### ISSUE TITLE
[Bug] Socket.io not available on Https server.

### ISSUE THREAD

**Issue by Kapulara** [Romakita/ts-express-decorators#193]
## Informations

Type | Version
---|---
Bug | 2.18.1

****

## Description
When using a SocketService for a certain namespace it adds that namespace to "/socket.io" route.

However trying to connect to this route on port 8000 gives GET 404 "Cannot get /socket.io".

## Todos

- [ ] Generate SSL keys
- [ ] Supply them to httpsOptions in ServerSettings
- [ ] Create SocketService
- [ ] Validate if working by connecting socket.io to http://localhost:8080/namespace
- [ ] Check https variant: https://localhost:8000/namespace and notice a GET 404 "Cannot get /socket.io".

**Comment by Romakita** [comment]
Hi @Kapulara ,

I tried the namespace and it works fine for me (in http). Example here work : https://github.com/NodeLabs/techday-node/tree/solution (this is my showcase :p).

For https I'm not sure how I can configure the socket server. If you have an idea, here the method that initialize the socket server : https://github.com/Romakita/ts-express-decorators/blob/master/src/socketio/services/SocketIOService.ts#L27-L41

**Comment by Kapulara** [comment]
@Romakita #194 😄

**Comment by Romakita** [comment]
@Kapulara Can I close this issue ?
